
services:
  # MySQL Database (Data Source)
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coal_mining
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/production_logs.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mining_network

  # ClickHouse Database (Data Warehouse)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-db
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: coal_mining_dw
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    networks:
      - mining_network

  # Python Environment for ETL Scripts
  etl-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl-runner
    depends_on:
      - mysql
      - clickhouse
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=coal_mining
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DATABASE=coal_mining_dw
    networks:
      - mining_network
    command: tail -f /dev/null  # Keep container running

volumes:
  mysql_data:
  clickhouse_data:

networks:
  mining_network:
    driver: bridge